---
language: node_js
node_js:
- '0.10'
- '0.8'
- '0.6'
script: npm run-script ci
env:
  global:
  - BUSTER_TEST_OPT="--reporter specification"
  - SELENIUM_USERNAME=cujojs-rest
  - secure: "kxs2tHuJ3Vd1lO/mBoUJ5EpLdojYuAsCGm7xP03VVjuuJs7zf1gux3xx3e+5\nb2LaZL4p4/rPmkPaYGNmh/FE2XrmcAejF1bSKyX0VLD0LUPnB/afwWMF1vvI\nupa+JAXxNlM2tNaK+TiLdq0uFhjs8GyTdxHm9jujdzOmGf7IF8o="
